#! /bin/bash

# To avoid installing any of these components, comment out the corresponding line(s) below
INSTALL_PROXYCHAINS_NG="unzip ca-certificates curl libc6-dev gcc make"
INSTALL_POLIPO="polipo"
# ###

apt update && apt install -y --no-install-recommends shadowsocks-libev ${INSTALL_PROXYCHAINS_NG} ${INSTALL_POLIPO}

echo "Enter your desired shadowsocks local port (press ENTER for default, 1080):"
read LOCAL_PORT
[ -z "${LOCAL_PORT}" ] && LOCAL_PORT=1080

SS_CONFIG_PATH="/etc/shadowsocks-libev/okss.client.json"

echo "Paste your shadowsocks client config json (or press ENTER to skip):"
echo "If you're not pasting the snippet generated by this project, you may need to make sure it works yourself."
while read LINE; do
	[ -z "${LINE}" ] && break
	[ "${FILE_CLEAR}" ] || (touch ${SS_CONFIG_PATH} && truncate -s 0 ${SS_CONFIG_PATH}) && FILE_CLEAR="y"
	if [[ "${LINE}" =~ '"local_port"' ]]; then
		continue
	fi
	echo "${LINE}" >> ${SS_CONFIG_PATH}
	[ "${LINE}" == '}' ] && break
done

if [ "${LINE}" == '}' ]; then
	sed -i "5i\"local_port\":${LOCAL_PORT}," ${SS_CONFIG_PATH}
fi

echo ""

systemctl enable --now shadowsocks-libev-local@okss.client
systemctl restart shadowsocks-libev-local@okss.client

if [ "${INSTALL_PROXYCHAINS_NG}" ]; then
	echo "Building proxychains-ng..."
	TMP_DIR="$(mktemp -d)"
	ORIG_DIR="$(pwd)"
	curl -vL https://github.com/rofl0r/proxychains-ng/archive/master.zip -o "${TMP_DIR}/proxychains-ng.zip"
	unzip "${TMP_DIR}/proxychains-ng.zip" -d "${TMP_DIR}/build"
	cd "${TMP_DIR}/build/proxychains-ng-master"
	./configure --prefix=/usr --sysconfdir=/etc
	make install
	make install-config
	sed -i "s/socks4 	127.0.0.1 9050/socks5	127.0.0.1 ${LOCAL_PORT}/" /etc/proxychains.conf
	cd "${ORIG_DIR}"
	rm -rf "${TMP_DIR}"
fi

POLIPO_CONFIG_PATH="/etc/polipo/config"

if [ "${INSTALL_POLIPO}" ]; then
	echo "Configuring polipo..."
	grep -qiP 'socksParentProxy=*' /etc/polipo/config
	if [ "$?" -eq 0 ]; then
		sed -iE "s/socksParentProxy=.*/socksParentProxy=localhost:${LOCAL_PORT}/" ${POLIPO_CONFIG_PATH}
	else
		echo "socksParentProxy=localhost:${LOCAL_PORT}" >> ${POLIPO_CONFIG_PATH}
	fi
	systemctl restart polipo
fi

echo "Script finished."
